[package]
name = "thunderscope"
version = "0.1.0"
edition = "2021"

[dependencies]
bipbuffer = "0.1.2"
bitflags = "2.6.0"
env_logger = "0.11.3"
libc = "0.2.155"
log = "0.4.22"

[[bin]]
name = "thunderscope-test"
